### ISSUE TITLE
Why does vlmul only occupy 2 bits in v_csr?

### ISSUE THREAD

**Issue by jlong299** [semidynamics/OpenVectorInterface#1]
Why does vlmul only occupy 2 bits in issue.v_csr ([35:34])? Dose that mean the case of LMUL < 1 is not supported?

**Comment by jlong299** [comment]
And where does VPU obtain the mask-agnostic and tail-agnostic (vma/vta)?  Thanks.

**Comment by amorenosmd** [comment]
OVI currently supports Vector extension [v0.7.1](https://github.com/riscv/riscv-v-spec/blob/0.7.1/v-spec.adoc). In this version, fractional LMUL is not supported and is decoded with just 2 bits. Similarly, VMA/VTA were not yet introduced.

We are currently working on an updated version that supports v1.0 and includes these features.

**Comment by jlong299** [comment]
Got it. Thank you so much.
