### ISSUE TITLE
How does VPU know which one of the set {1, 2, 4, -1, -2, -4} is the load-stride value?

### ISSUE THREAD

**Issue by jlong299** [semidynamics/OpenVectorInterface#2]
How does VPU know which one of the set {1, 2, 4, -1, -2, -4} is the load-stride value?
Does it obtain the value from ISSUE: scalar_opnd? Which will choose rs2 instead of rs1 for case of load/store instruction.
Thanks.

**Comment by amorenosmd** [comment]
Correct. ISSUE sets the scalar register needed by the VPU: for strided memory operations, this is rs2 and contains the stride. Note that the stride is in bytes, but the set of fast strides is defined as elements of size SEW. This means that the VPU still needs to do a step of conversion from byte stride to element stride (i.e. (byte-stride)>>SEW).
