### ISSUE TITLE
Maximum number of elements in one unit-load 

### ISSUE THREAD

**Issue by jlong299** [semidynamics/OpenVectorInterface#3]
In 9.2.1 (page16) there is a statement "The following examples assume a SEW of 32b, which implies, for a 512b cache line, up to 16
elements. Additionally, an LMUL=1 means that a load fetches up to 512 elements. ".
Why a load can fetch 512 elements? As my understanding, if sew=32, LMUL=1 and VLEN=512, the answer should be 512/32 = 16 elements.
Thanks.

**Comment by amorenosmd** [comment]
The buses in the OVI are sized to accommodate VPUs with very large vector registers, up to VLEN=16384b. In this case, the maximum number of elements that a single vector load can fetch is 512 elements (16384/32=512). The line you quote makes reference to this fact (perhaps a bit too cryptically), implying that the element ID will be smaller to that number.
