### ISSUE TITLE
Clarification on Segment Load/Stores in Version 1.05

### ISSUE THREAD

**Issue by dxie-tt** [semidynamics/OpenVectorInterface#5]
Hello,

I've been reviewing the Open Vector Interface specification (version 1.05) and I have a question regarding segment load/stores. I noticed that there's no explicit mention of segment load/stores in the document.

The 512b LOAD/STORE interfaces seem to suggest that they should be handled on a per-element basis, given that the largest segment size is 8 (LMUL) x 64 (VSEW) = 512b.

Could you please provide some clarification on how segment load/stores are handled according to the current specification? Any additional information or guidance would be greatly appreciated.

Thank you in advance for your assistance.

Best regards,
DJ

**Comment by amorenosmd** [comment]
Hi,

This version of the OVI only supports the RISC-V vector spec [v0.7.1](https://github.com/riscv/riscv-v-spec/blob/0.7.1/v-spec.adoc). In this version, segment load/stores were an optional extension and not supported by OVI.

We are currently working on the next major revision of OVI which adds support for v1.0, which will include support for segment loads and stores.

**Comment by dxie-tt** [comment]
Thank you for the clarification. I appreciate your prompt and detailed response. 
I'm looking forward to the next major revision of OVI that will add support for v1.0, including segment loads and stores. This will be a significant update and I'm excited to see the new features and improvements.

Thanks again for your time and assistance.

Best regards,
DJ
