### ISSUE TITLE
Regarding dispatch.kill signal

### ISSUE THREAD

**Issue by ystozlu-tt** [semidynamics/OpenVectorInterface#6]
In the spec, on page 9, the following is stated, 

```
- dispatch.kill: If set, the instruction with ID dispatch.sb_id was incorrectly issued and must
be killed. Any Avispado or VPU state updated by this instruction must be reverted. This
signal also implies that any younger instruction will have to be killed too.
```
The next paragraph states something slightly different,

```
In particular, this means that, on instruction kill, Avispado is responsible for sending kill requests for every
instruction that is killed as a result of a failed speculation. 
```

The first paragraph suggests that only one kill signal (i.e. 1 cycle) should be sent to the VPU along with the ```sb_id``` of the the **oldest of the misspeculated instruction**. The younger misspeculated instructions should be killed by the VPU, but there will be no explicit kill signals for the younger instructions. 

The second paragraph suggests that there needs to be a kill signal for every single instruction that is killed. This seems redundant as killing an older instruction implies killing younger ones. It also complicates the recovery process, as the CPU needs to send multiple kill signals with every recovery.

In this case, which approach is correct?

Thank you,

**Comment by amorenosmd** [comment]
When dispatch.kill is set, the instruction with the matching ID and every younger instruction will be killed. This should technically suffice but, even so, the core must send the ID for every instruction that is killed. The VPU can safely make the assumption that it will receive a kill signal for every younger instruction. This gives two options to the VPU: proactively kill every younger instruction and ignore the following kill signals or wait for the kill signal for every instruction.
