### ISSUE TITLE
Questions on UNALIGNED Exception, Retry/Trap Differentiation, Mask_idx Interface, and Dispatch Kill Order

### ISSUE THREAD

**Issue by dxie-tt** [semidynamics/OpenVectorInterface#7]
Hello,

I've been reviewing the Open Vector Interface specification and I have a few questions that I hope you could help clarify:

1. UNALIGNED Exception: The spec mentions that `any vector memory operation (load or store) whose elements are not naturally aligned to memory in their Standard Element Width will eventually cause an UNALIGNED exception. `It seems that the VPU can only detect the unalignment for unit-stride load/store, and issue illegal complete before sending memop.sync_start. For strided and indexed operations, it appears that the VPU cannot detect unaligned addresses. It seems like the UNALIGNED exception may need to be detected in the CPU, but the existing memop interface cannot differentiate between an illegal op and an exception op. Could you please clarify this?

2. Retry and Trap: How does a CPU differentiate between retry and trap from the completed interface? It seems that the CPU has to behave differently for retry and trap, but it's not clear how this differentiation is made.

3. Mask_idx Interface for Non-indexed Load/Store: The spec does not clearly explain how the mask is transferred from the VPU to the CPU for unit-stride and strided load/store. Should the VPU send the mask in packed chunks, similar to store data? For example, when vstart=0, should it send the mask bits of the first 64 elements on the first transfer, and then the mask bits for elements 64-127 on the next transfer?

4. Dispatch Kill Order with Younger Issue: There seems to be an implicit requirement that dispatch kill has to be sent first before the CPU can issue the younger vector instructions that are fetched from the correct path. Could you please confirm this?

Any additional information or guidance would be greatly appreciated.

Thank you in advance for your assistance.

Best regards,
DJ

**Comment by amorenosmd** [comment]
Hi,

1. The VPU will only detect illegal instruction exceptions. Unaligned exceptions, or any other memory exception, must be detected by the Core. In fact, the Core is the only one that can detect them, since the VPU doesn't have access to the base virtual address or the physical address after translation. It is expected that the TLB, PMA and PMPs are solely accessed by the core, in order to simplify the overall design.

2. Since the VPU cannot detect any memory exceptions, setting a vstart different than zero is exclusively used to indicate a retry. Thus, the VPU will indicate a retry by diving vstart to a non-zero value.

3. There is information about strided load/store masks in section 9.2.2. The mask is sent by driving the 64 LSBs of the mask_idx.item signal, in packs of 64 elements. With vstart = 0 the mask is transmitted exactly as you mention: first elements 0 to 63, then elements 64 to 127 and so on.

4. Yes, this is correct.

**Comment by dxie-tt** [comment]
Thank you for your clarification.

I have a follow-up question about the retry mechanism. From what I understand, the Core handles memory exceptions, and the VPU initiates a retry when necessary. The example in Figure 14 suggests that the VPU decides to retry element 5 after receiving the load data 5. However, the LOAD interface doesn't seem to have a field indicating a faulty load.

Could you please provide an example or scenario where the VPU would need to initiate a retry? I'm finding it challenging to envision such a case.

Thank you in advance for your assistance.

**Comment by amorenosmd** [comment]
The retry is an optional feature that may be required by the VPU. The idea behind this feature is to allow simplifying certain VPU designs. When performing a vector load, the accessed memory lines may come in an arbitrary order that depends on the memory hierarchy (hit/miss in L1, L2, L3, and so on). This adds an extra challenge to the VPU, which now needs to either be always ready to write a line into its register file or to buffer this data until after the register file is ready for writing. 

OVI was designed for large VLENs in mind, and, in these cases, the number of in-flight memory lines can be large. This means that the VPU may need to have very large buffers for reordering memory lines. To limit the cost of these types of implementations, the retry is intended to be used by the VPU for cases in which it runs out of buffering space. Of course, this retry comes with a high cost in performance, so its use should be limited to very uncommon corner cases.

Implementations that don't need this feature may hardwire vstart to 0 and ignore it altogether.

**Comment by dxie-tt** [comment]
Thank you for the detailed example. It's much clearer now.

I have one final question: If a VPU implementation doesn't require this retry feature and the companion core doesn't support it either, would this make the core non-compliant with OVI? Could this feature be optional?

**Comment by amorenosmd** [comment]
Yes, this could be an optional feature if the VPU doesn't require it. There is no advantage in using this feature if it's not necessary.

**Comment by dxie-tt** [comment]
I greatly appreciate your patience and the helpful information you've provided. Thank you so much!
