### ISSUE TITLE
Questions regarding VL and load / store communications between CPU and VPU

### ISSUE THREAD

**Issue by kychentt** [semidynamics/OpenVectorInterface#8]
Hi, I have the following questions regarding load / store requests between the VPU and the CPU.
1. For non-indexed load / store, is the VPU required to send VLmax amount of mask or just VL amount of mask?

2. Following the previous question, when CPU is sending load data response back to the VPU, should it return VLmax amount of response or VL amount of response? We understand that response are still required when the load element is masked-off.

3. For indexed load / store and the last_idx signal, should the number of load response match the number of requests up till the last_idx signal?

Thank you.

**Comment by amorenosmd** [comment]
1. It is enough to just send up to VL. Note that elements below vstart are also not sent.
2. The Core will transmit only VL elements. As you mention, responses are required for masked-off elements too.
3. Yes.

**Comment by kychentt** [comment]
Thank you for your reply and I have some follow up questions on questions 1 and 2.
1. In a store scenario, 
   a. when 0 < vl < vlMax, does the VPU transfer vl or VlMax amount of data to the CPU?
2. In the case where there is no valid element to be sent (vl = 0 or vstart >= vl), do we:
   a. need to send memop_sync_start / memop_sync_end
   b. need to send store data, if so, how many elements
   c. need to send mask (if it's not index load / store)
   d. need to send index (if it's index load / store)
   e. need to send load response, if so, how many elements.

**Comment by amorenosmd** [comment]
1. The VPU only needs to send VL data.
2. sync_start and sync_end should be sent, but no need for any data exchange between Core and VPU, regardless of the operation type.

**Comment by kychentt** [comment]
Thank you so much!
